version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:18
    container_name: dcs-api
    env_file: .env
    restart: always
    ports:
      - "8181:8080"
    volumes:
      - .:/home/node/app
    # command: ["npm", "run", "dev"] # Use nodemon for development